system:
    default:
        field_templates:
            - {template: EzSystemsGpxFieldTypeBundle:fields:ezgpx.html.twig, priority: 0}
        fielddefinition_settings_templates:
            - {template: EzSystemsGpxFieldTypeBundle:platformui/content_type/view:ezgpx.html.twig, priority: 0}
